//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/_Main/Scriptables/Input/Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Actions"",
    ""maps"": [
        {
            ""name"": ""Walking"",
            ""id"": ""f351c44e-8a2f-4f87-9071-87cdc42c7e54"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""fffb72e5-8069-4f91-9ebc-679df0ec5b57"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""ce403746-3cd2-43d9-abe1-e506f1ca7884"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quests"",
                    ""type"": ""Button"",
                    ""id"": ""aea4a1ca-7248-4acf-a111-44e3cf57c364"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""5d8cba40-d314-4c20-b57b-cd917def9671"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""29431ce2-4177-4496-a3e8-c0b785247e3e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""On Foot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""56c220b8-caff-4ff3-92ab-3f188cb92039"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""On Foot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fb53c25c-242c-4ce4-b26d-06d97741ec71"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""On Foot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""41ae133b-02f3-4d24-a8b0-63c5dce45d6e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""On Foot;Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""39298070-bae9-4a4b-ba13-0ed9652a2d68"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1f7dada-0a2d-450a-8bbf-61a829bff5e4"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Quests"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Talking"",
            ""id"": ""9776ee44-8653-4289-953f-0154cb7942e6"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""a52a55b4-10ef-4c23-bf60-242f6a25e57b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5e69f5b4-1afd-41d0-81a6-a60b5f118baf"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Choosing"",
            ""id"": ""d0201738-bd5c-4db5-97f9-ae6d62b6b7c8"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""5bbae46c-d110-4f98-8bc0-c5eaeab8fe27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Next"",
                    ""type"": ""Button"",
                    ""id"": ""bb5a1dee-fdb5-4075-9915-feb3edbf2b1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Previous"",
                    ""type"": ""Button"",
                    ""id"": ""44dd8f38-ed87-4505-80a8-f88bca3e1a0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0d2ee826-a6cc-4582-95de-6d7d68371655"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ae5804b-d1d0-4072-bbf8-59f7c6464040"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28703f69-01b9-4ca9-ab28-02062739d368"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Previous"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Slider"",
            ""id"": ""c9ab0a6a-b0c2-4b3d-8a7d-c15eb6f9ae35"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""1170bb8c-32fd-460e-9313-987350cacb10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7e15eb0e-d3a1-415b-99ad-81418d8ef465"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Unity Editor"",
            ""id"": ""e1afbf7f-0253-48e2-91af-daae12805432"",
            ""actions"": [
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""cdf83d9c-f3d0-4a6b-966d-79a7c0ebd7ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8f491c18-80bd-4a2e-af6c-00b095d5a27d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""In-game"",
            ""id"": ""13044975-37d5-4f15-bb78-8833b6b93ffa"",
            ""actions"": [
                {
                    ""name"": ""Backpack menu"",
                    ""type"": ""Button"",
                    ""id"": ""c55b4f52-140b-4ed0-a201-9b3f4cd869bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settings menu"",
                    ""type"": ""Button"",
                    ""id"": ""b3238317-bf21-430c-8a81-6d8591eabd1c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4c3246bf-c83f-4dc6-bc86-67f4eb195928"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Backpack menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36dde1a4-676a-4237-b0ec-2f549fc48cce"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Settings menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""In-game Menu"",
            ""id"": ""b031db69-9d5d-4076-b126-db60a5c1fdd7"",
            ""actions"": [
                {
                    ""name"": ""Exit "",
                    ""type"": ""Button"",
                    ""id"": ""b304ce11-9473-4e61-801e-9c6f9f6859ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settings menu"",
                    ""type"": ""Button"",
                    ""id"": ""dd071c73-e287-4c25-a33c-06e9e02e64ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backpack menu"",
                    ""type"": ""Button"",
                    ""id"": ""4d53f75d-8fb1-4949-abce-382667562653"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ebb5079b-8fb9-47f3-83ec-a49b0bb5a883"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Exit "",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac3c1b98-339b-41a9-b124-4f8519e6c39e"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Backpack menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccb0fbba-a971-49c6-93e0-7dda2b9e45db"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Settings menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Storage"",
            ""id"": ""d21f6d29-f414-45da-a4a2-c808b931de86"",
            ""actions"": [
                {
                    ""name"": ""Exit "",
                    ""type"": ""Button"",
                    ""id"": ""379b561c-eee6-4968-ab88-38505a1c47de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""25bcb6ea-f5eb-46db-a7ce-02ce61132e93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""14ca2ade-27c5-4453-9764-9375206079c8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Exit "",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3996c892-97f5-4b83-888c-38ae1e022b37"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BrowsingQuests"",
            ""id"": ""c26f10ed-4b45-4c90-bf65-b7321dd44f0a"",
            ""actions"": [
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""ba077e33-f916-47a6-b7c5-88b02021370e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Next"",
                    ""type"": ""Button"",
                    ""id"": ""60554597-25e2-49a4-b72a-f4cd270c87da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Previous"",
                    ""type"": ""Button"",
                    ""id"": ""4cd67b2d-479d-448e-aa2b-1b1bf6631faa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""23077b5e-8ab3-4df4-bafd-4e06e4815b07"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1510ca47-c05f-49a7-a324-b9b128e05783"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfd73308-fd23-4bb1-8a27-7799c35c3aec"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Previous"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Walking
        m_Walking = asset.FindActionMap("Walking", throwIfNotFound: true);
        m_Walking_Movement = m_Walking.FindAction("Movement", throwIfNotFound: true);
        m_Walking_Interact = m_Walking.FindAction("Interact", throwIfNotFound: true);
        m_Walking_Quests = m_Walking.FindAction("Quests", throwIfNotFound: true);
        // Talking
        m_Talking = asset.FindActionMap("Talking", throwIfNotFound: true);
        m_Talking_Interact = m_Talking.FindAction("Interact", throwIfNotFound: true);
        // Choosing
        m_Choosing = asset.FindActionMap("Choosing", throwIfNotFound: true);
        m_Choosing_Interact = m_Choosing.FindAction("Interact", throwIfNotFound: true);
        m_Choosing_Next = m_Choosing.FindAction("Next", throwIfNotFound: true);
        m_Choosing_Previous = m_Choosing.FindAction("Previous", throwIfNotFound: true);
        // Slider
        m_Slider = asset.FindActionMap("Slider", throwIfNotFound: true);
        m_Slider_Interact = m_Slider.FindAction("Interact", throwIfNotFound: true);
        // Unity Editor
        m_UnityEditor = asset.FindActionMap("Unity Editor", throwIfNotFound: true);
        m_UnityEditor_Escape = m_UnityEditor.FindAction("Escape", throwIfNotFound: true);
        // In-game
        m_Ingame = asset.FindActionMap("In-game", throwIfNotFound: true);
        m_Ingame_Backpackmenu = m_Ingame.FindAction("Backpack menu", throwIfNotFound: true);
        m_Ingame_Settingsmenu = m_Ingame.FindAction("Settings menu", throwIfNotFound: true);
        // In-game Menu
        m_IngameMenu = asset.FindActionMap("In-game Menu", throwIfNotFound: true);
        m_IngameMenu_Exit = m_IngameMenu.FindAction("Exit ", throwIfNotFound: true);
        m_IngameMenu_Settingsmenu = m_IngameMenu.FindAction("Settings menu", throwIfNotFound: true);
        m_IngameMenu_Backpackmenu = m_IngameMenu.FindAction("Backpack menu", throwIfNotFound: true);
        // Storage
        m_Storage = asset.FindActionMap("Storage", throwIfNotFound: true);
        m_Storage_Exit = m_Storage.FindAction("Exit ", throwIfNotFound: true);
        m_Storage_Move = m_Storage.FindAction("Move", throwIfNotFound: true);
        // BrowsingQuests
        m_BrowsingQuests = asset.FindActionMap("BrowsingQuests", throwIfNotFound: true);
        m_BrowsingQuests_Quit = m_BrowsingQuests.FindAction("Quit", throwIfNotFound: true);
        m_BrowsingQuests_Next = m_BrowsingQuests.FindAction("Next", throwIfNotFound: true);
        m_BrowsingQuests_Previous = m_BrowsingQuests.FindAction("Previous", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Walking
    private readonly InputActionMap m_Walking;
    private List<IWalkingActions> m_WalkingActionsCallbackInterfaces = new List<IWalkingActions>();
    private readonly InputAction m_Walking_Movement;
    private readonly InputAction m_Walking_Interact;
    private readonly InputAction m_Walking_Quests;
    public struct WalkingActions
    {
        private @InputActions m_Wrapper;
        public WalkingActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Walking_Movement;
        public InputAction @Interact => m_Wrapper.m_Walking_Interact;
        public InputAction @Quests => m_Wrapper.m_Walking_Quests;
        public InputActionMap Get() { return m_Wrapper.m_Walking; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WalkingActions set) { return set.Get(); }
        public void AddCallbacks(IWalkingActions instance)
        {
            if (instance == null || m_Wrapper.m_WalkingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WalkingActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Quests.started += instance.OnQuests;
            @Quests.performed += instance.OnQuests;
            @Quests.canceled += instance.OnQuests;
        }

        private void UnregisterCallbacks(IWalkingActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Quests.started -= instance.OnQuests;
            @Quests.performed -= instance.OnQuests;
            @Quests.canceled -= instance.OnQuests;
        }

        public void RemoveCallbacks(IWalkingActions instance)
        {
            if (m_Wrapper.m_WalkingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWalkingActions instance)
        {
            foreach (var item in m_Wrapper.m_WalkingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WalkingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WalkingActions @Walking => new WalkingActions(this);

    // Talking
    private readonly InputActionMap m_Talking;
    private List<ITalkingActions> m_TalkingActionsCallbackInterfaces = new List<ITalkingActions>();
    private readonly InputAction m_Talking_Interact;
    public struct TalkingActions
    {
        private @InputActions m_Wrapper;
        public TalkingActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Talking_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Talking; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TalkingActions set) { return set.Get(); }
        public void AddCallbacks(ITalkingActions instance)
        {
            if (instance == null || m_Wrapper.m_TalkingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TalkingActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(ITalkingActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(ITalkingActions instance)
        {
            if (m_Wrapper.m_TalkingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITalkingActions instance)
        {
            foreach (var item in m_Wrapper.m_TalkingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TalkingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TalkingActions @Talking => new TalkingActions(this);

    // Choosing
    private readonly InputActionMap m_Choosing;
    private List<IChoosingActions> m_ChoosingActionsCallbackInterfaces = new List<IChoosingActions>();
    private readonly InputAction m_Choosing_Interact;
    private readonly InputAction m_Choosing_Next;
    private readonly InputAction m_Choosing_Previous;
    public struct ChoosingActions
    {
        private @InputActions m_Wrapper;
        public ChoosingActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Choosing_Interact;
        public InputAction @Next => m_Wrapper.m_Choosing_Next;
        public InputAction @Previous => m_Wrapper.m_Choosing_Previous;
        public InputActionMap Get() { return m_Wrapper.m_Choosing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ChoosingActions set) { return set.Get(); }
        public void AddCallbacks(IChoosingActions instance)
        {
            if (instance == null || m_Wrapper.m_ChoosingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ChoosingActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Next.started += instance.OnNext;
            @Next.performed += instance.OnNext;
            @Next.canceled += instance.OnNext;
            @Previous.started += instance.OnPrevious;
            @Previous.performed += instance.OnPrevious;
            @Previous.canceled += instance.OnPrevious;
        }

        private void UnregisterCallbacks(IChoosingActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Next.started -= instance.OnNext;
            @Next.performed -= instance.OnNext;
            @Next.canceled -= instance.OnNext;
            @Previous.started -= instance.OnPrevious;
            @Previous.performed -= instance.OnPrevious;
            @Previous.canceled -= instance.OnPrevious;
        }

        public void RemoveCallbacks(IChoosingActions instance)
        {
            if (m_Wrapper.m_ChoosingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IChoosingActions instance)
        {
            foreach (var item in m_Wrapper.m_ChoosingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ChoosingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ChoosingActions @Choosing => new ChoosingActions(this);

    // Slider
    private readonly InputActionMap m_Slider;
    private List<ISliderActions> m_SliderActionsCallbackInterfaces = new List<ISliderActions>();
    private readonly InputAction m_Slider_Interact;
    public struct SliderActions
    {
        private @InputActions m_Wrapper;
        public SliderActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Slider_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Slider; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SliderActions set) { return set.Get(); }
        public void AddCallbacks(ISliderActions instance)
        {
            if (instance == null || m_Wrapper.m_SliderActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SliderActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(ISliderActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(ISliderActions instance)
        {
            if (m_Wrapper.m_SliderActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISliderActions instance)
        {
            foreach (var item in m_Wrapper.m_SliderActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SliderActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SliderActions @Slider => new SliderActions(this);

    // Unity Editor
    private readonly InputActionMap m_UnityEditor;
    private List<IUnityEditorActions> m_UnityEditorActionsCallbackInterfaces = new List<IUnityEditorActions>();
    private readonly InputAction m_UnityEditor_Escape;
    public struct UnityEditorActions
    {
        private @InputActions m_Wrapper;
        public UnityEditorActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Escape => m_Wrapper.m_UnityEditor_Escape;
        public InputActionMap Get() { return m_Wrapper.m_UnityEditor; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UnityEditorActions set) { return set.Get(); }
        public void AddCallbacks(IUnityEditorActions instance)
        {
            if (instance == null || m_Wrapper.m_UnityEditorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UnityEditorActionsCallbackInterfaces.Add(instance);
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
        }

        private void UnregisterCallbacks(IUnityEditorActions instance)
        {
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
        }

        public void RemoveCallbacks(IUnityEditorActions instance)
        {
            if (m_Wrapper.m_UnityEditorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUnityEditorActions instance)
        {
            foreach (var item in m_Wrapper.m_UnityEditorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UnityEditorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UnityEditorActions @UnityEditor => new UnityEditorActions(this);

    // In-game
    private readonly InputActionMap m_Ingame;
    private List<IIngameActions> m_IngameActionsCallbackInterfaces = new List<IIngameActions>();
    private readonly InputAction m_Ingame_Backpackmenu;
    private readonly InputAction m_Ingame_Settingsmenu;
    public struct IngameActions
    {
        private @InputActions m_Wrapper;
        public IngameActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Backpackmenu => m_Wrapper.m_Ingame_Backpackmenu;
        public InputAction @Settingsmenu => m_Wrapper.m_Ingame_Settingsmenu;
        public InputActionMap Get() { return m_Wrapper.m_Ingame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IngameActions set) { return set.Get(); }
        public void AddCallbacks(IIngameActions instance)
        {
            if (instance == null || m_Wrapper.m_IngameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_IngameActionsCallbackInterfaces.Add(instance);
            @Backpackmenu.started += instance.OnBackpackmenu;
            @Backpackmenu.performed += instance.OnBackpackmenu;
            @Backpackmenu.canceled += instance.OnBackpackmenu;
            @Settingsmenu.started += instance.OnSettingsmenu;
            @Settingsmenu.performed += instance.OnSettingsmenu;
            @Settingsmenu.canceled += instance.OnSettingsmenu;
        }

        private void UnregisterCallbacks(IIngameActions instance)
        {
            @Backpackmenu.started -= instance.OnBackpackmenu;
            @Backpackmenu.performed -= instance.OnBackpackmenu;
            @Backpackmenu.canceled -= instance.OnBackpackmenu;
            @Settingsmenu.started -= instance.OnSettingsmenu;
            @Settingsmenu.performed -= instance.OnSettingsmenu;
            @Settingsmenu.canceled -= instance.OnSettingsmenu;
        }

        public void RemoveCallbacks(IIngameActions instance)
        {
            if (m_Wrapper.m_IngameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IIngameActions instance)
        {
            foreach (var item in m_Wrapper.m_IngameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_IngameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public IngameActions @Ingame => new IngameActions(this);

    // In-game Menu
    private readonly InputActionMap m_IngameMenu;
    private List<IIngameMenuActions> m_IngameMenuActionsCallbackInterfaces = new List<IIngameMenuActions>();
    private readonly InputAction m_IngameMenu_Exit;
    private readonly InputAction m_IngameMenu_Settingsmenu;
    private readonly InputAction m_IngameMenu_Backpackmenu;
    public struct IngameMenuActions
    {
        private @InputActions m_Wrapper;
        public IngameMenuActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Exit => m_Wrapper.m_IngameMenu_Exit;
        public InputAction @Settingsmenu => m_Wrapper.m_IngameMenu_Settingsmenu;
        public InputAction @Backpackmenu => m_Wrapper.m_IngameMenu_Backpackmenu;
        public InputActionMap Get() { return m_Wrapper.m_IngameMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IngameMenuActions set) { return set.Get(); }
        public void AddCallbacks(IIngameMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_IngameMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_IngameMenuActionsCallbackInterfaces.Add(instance);
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @Settingsmenu.started += instance.OnSettingsmenu;
            @Settingsmenu.performed += instance.OnSettingsmenu;
            @Settingsmenu.canceled += instance.OnSettingsmenu;
            @Backpackmenu.started += instance.OnBackpackmenu;
            @Backpackmenu.performed += instance.OnBackpackmenu;
            @Backpackmenu.canceled += instance.OnBackpackmenu;
        }

        private void UnregisterCallbacks(IIngameMenuActions instance)
        {
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @Settingsmenu.started -= instance.OnSettingsmenu;
            @Settingsmenu.performed -= instance.OnSettingsmenu;
            @Settingsmenu.canceled -= instance.OnSettingsmenu;
            @Backpackmenu.started -= instance.OnBackpackmenu;
            @Backpackmenu.performed -= instance.OnBackpackmenu;
            @Backpackmenu.canceled -= instance.OnBackpackmenu;
        }

        public void RemoveCallbacks(IIngameMenuActions instance)
        {
            if (m_Wrapper.m_IngameMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IIngameMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_IngameMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_IngameMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public IngameMenuActions @IngameMenu => new IngameMenuActions(this);

    // Storage
    private readonly InputActionMap m_Storage;
    private List<IStorageActions> m_StorageActionsCallbackInterfaces = new List<IStorageActions>();
    private readonly InputAction m_Storage_Exit;
    private readonly InputAction m_Storage_Move;
    public struct StorageActions
    {
        private @InputActions m_Wrapper;
        public StorageActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Exit => m_Wrapper.m_Storage_Exit;
        public InputAction @Move => m_Wrapper.m_Storage_Move;
        public InputActionMap Get() { return m_Wrapper.m_Storage; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StorageActions set) { return set.Get(); }
        public void AddCallbacks(IStorageActions instance)
        {
            if (instance == null || m_Wrapper.m_StorageActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StorageActionsCallbackInterfaces.Add(instance);
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IStorageActions instance)
        {
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IStorageActions instance)
        {
            if (m_Wrapper.m_StorageActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStorageActions instance)
        {
            foreach (var item in m_Wrapper.m_StorageActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StorageActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StorageActions @Storage => new StorageActions(this);

    // BrowsingQuests
    private readonly InputActionMap m_BrowsingQuests;
    private List<IBrowsingQuestsActions> m_BrowsingQuestsActionsCallbackInterfaces = new List<IBrowsingQuestsActions>();
    private readonly InputAction m_BrowsingQuests_Quit;
    private readonly InputAction m_BrowsingQuests_Next;
    private readonly InputAction m_BrowsingQuests_Previous;
    public struct BrowsingQuestsActions
    {
        private @InputActions m_Wrapper;
        public BrowsingQuestsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Quit => m_Wrapper.m_BrowsingQuests_Quit;
        public InputAction @Next => m_Wrapper.m_BrowsingQuests_Next;
        public InputAction @Previous => m_Wrapper.m_BrowsingQuests_Previous;
        public InputActionMap Get() { return m_Wrapper.m_BrowsingQuests; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BrowsingQuestsActions set) { return set.Get(); }
        public void AddCallbacks(IBrowsingQuestsActions instance)
        {
            if (instance == null || m_Wrapper.m_BrowsingQuestsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BrowsingQuestsActionsCallbackInterfaces.Add(instance);
            @Quit.started += instance.OnQuit;
            @Quit.performed += instance.OnQuit;
            @Quit.canceled += instance.OnQuit;
            @Next.started += instance.OnNext;
            @Next.performed += instance.OnNext;
            @Next.canceled += instance.OnNext;
            @Previous.started += instance.OnPrevious;
            @Previous.performed += instance.OnPrevious;
            @Previous.canceled += instance.OnPrevious;
        }

        private void UnregisterCallbacks(IBrowsingQuestsActions instance)
        {
            @Quit.started -= instance.OnQuit;
            @Quit.performed -= instance.OnQuit;
            @Quit.canceled -= instance.OnQuit;
            @Next.started -= instance.OnNext;
            @Next.performed -= instance.OnNext;
            @Next.canceled -= instance.OnNext;
            @Previous.started -= instance.OnPrevious;
            @Previous.performed -= instance.OnPrevious;
            @Previous.canceled -= instance.OnPrevious;
        }

        public void RemoveCallbacks(IBrowsingQuestsActions instance)
        {
            if (m_Wrapper.m_BrowsingQuestsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBrowsingQuestsActions instance)
        {
            foreach (var item in m_Wrapper.m_BrowsingQuestsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BrowsingQuestsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BrowsingQuestsActions @BrowsingQuests => new BrowsingQuestsActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IWalkingActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnQuests(InputAction.CallbackContext context);
    }
    public interface ITalkingActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IChoosingActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnNext(InputAction.CallbackContext context);
        void OnPrevious(InputAction.CallbackContext context);
    }
    public interface ISliderActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IUnityEditorActions
    {
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IIngameActions
    {
        void OnBackpackmenu(InputAction.CallbackContext context);
        void OnSettingsmenu(InputAction.CallbackContext context);
    }
    public interface IIngameMenuActions
    {
        void OnExit(InputAction.CallbackContext context);
        void OnSettingsmenu(InputAction.CallbackContext context);
        void OnBackpackmenu(InputAction.CallbackContext context);
    }
    public interface IStorageActions
    {
        void OnExit(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IBrowsingQuestsActions
    {
        void OnQuit(InputAction.CallbackContext context);
        void OnNext(InputAction.CallbackContext context);
        void OnPrevious(InputAction.CallbackContext context);
    }
}
